digest.go
verifiers.go

These exported items are no longer supported as of the splitting out of
this package. They will be maintained elsewhere for packages that are
currently using this as `distribution/digest`.
cc @dmcgowan @aaronlehmann

digest: remove deprecated interfaces

---

README.md
algorithm.go

digest: remove last of deprecated methods

---

MAINTAINERS

The [upstream example][1] only uses tabs.
[1]: https://github.com/docker/opensource/blob/4f64fe220fb497c82318ccacab0b9d2176b2ce84/project-template/MAINTAINERS

MAINTAINERS: Replace spaces with tabs

---

algorithm.go

algorithm: More new removal

---

LICENSE.code
LICENSE.docs
README.md

Before this commit, the README referenced a `LICENSE.docs` that didn't exist locally.  This commit copies the `LICENSE.code`, `LICENSE.docs`, and `README.md` blurb directly from the upstream repo.  The license text is from master with updated copyright year in `LICENSE.code`.  The `README.md` blurb is from [my cleanup PR][1] with an updated copyright year and the newlines removed (to match this repo's earlier blurb).
[1]: https://github.com/docker/opensource/pull/98

README: Cleanup licensing (add CC BY-SA 4.0 for docs, etc.)

---

digest.go

digest: remove out of date godoc comment

---

README.md

Circle CI, while nice, takes too much effort to maintain a Go build
verses travis. Removing the badge, which is the only part that mentions
circle.

README: remove circle badge

---

MAINTAINERS

Aaron and Derek have long been instrumental in the maintenance and
integration of the original `digest` package. Since this package
provides such critical functionality, having their experience on board
will ensure that additions to this package can be made with confidence.

MAINTAINERS: add new maintainers to go-digest

---

algorithm.go
digest.go
digest_test.go

In the past, we have had support for separators in the algorithm field
to allow parameterization of digest algorithms. A classic example is
`tarsum+sha256`. While this particular case is deprecated, support for
this case in the future must be allow in case we bring this back. This
will ensure that implementations these as valid digest, but correctly
report error when the algorithm is unsupported, rather than this being
treated as an invalid format.

digest: allow separators in algorithm field

---

algorithm.go
digest.go
digest_test.go

For https://github.com/opencontainers/image-spec/pull/667
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

disallow upper characters (/A-F/) in hex-encoded portion

---

README.md

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
https://github.com/opencontainers/org/issues/3

updating CoC link and security link

---

README.md
doc.go

Also fixes a typo and adds one clarifying link in the README.
Fixes #31

*: clarify we only deal with hex-encoded digests

---

.pullapprove.yml

The current configuration does not work with approvals, this configuration is mirrored from the distribution spec which does work correctly.

Update pull approve configuration

---

.mailmap
releases/README.md
releases/v1.0.0.toml

The release tag will be created from the merge commit of this PR. Applying an LGTM to this PR is voting for the release. Let's wait for a quorum to merge.
fixes https://github.com/opencontainers/go-digest/issues/46

Add release notes for v1.0.0

---

algorithm.go
algorithm_test.go
sha.go

This adds a new interface to go-digest allowing for it to act as a registry
for various hash implementations. It includes the new "CryptoHash" interface
which hashers must implement. By default the SHA variants that were
historically available are available.
The cryptoHash interface mimics crypto.Hash, but is a subset of the methods
that we require. crypto.Hash is a concrete type that makes it hard to bring
new hash function implementations in.
The primary impetus is to allow for out-of-tree hash implementations to be
added. For example, if someone wanted to add the out-of-tree BLAKE3 AVX
implementation, they could do that. Right now, if two versions of the same
implementation are added, the one that is added first will take precedence,
but in the future, we can add the ability to force …

Implement dynamic hash registration

---

algorithm_test.go
digestset/set_test.go
sha.go

This makes sure that the expected algorithms are registered when using this package.
Currently, the consumer of the package must import these, otherwise it's not registered, resultig in "unsupported digest algorithm" errors.
relates to https://github.com/moby/moby/pull/42755#issuecomment-901083537

make sure the standard algorithms are registered

---

algorithm.go
blake3/blake3.go
blake3/blake3_test.go
digest.go
digestset/set.go
digestset/set_test.go
doc.go
testdigest/testdigest.go
testdigest/testdigest_test.go

Both of these were deprecated in 55f675811a1b915549933c64571fd86b2676ba76 (https://github.com/opencontainers/go-digest/pull/33), but the format of the GoDoc comments didn't follow the correct format, which causes them not being picked up by tools as "deprecated".
This patch:
- Fixes the comments to be in the right format.
- Updates uses in the codebase to use the alternatives.
Also gofmt'd the code (first commit)

fix deprecation of NewDigestFromHex and Digest.Hex

---

.github/workflows/test.yml

Adds latest Go compiler versions to testing matrix.
Signed-off-by: Austin Vazquez <macedonv@amazon.com>

Add Go 1.18, 1.19, 1.20 to GitHub actions matrix

---

algorithm_test.go
digest.go
digest_test.go

Some changes I had locally (got some more, but in a follow-up) :smile:
These tests have to be in their own package to prevent a circular import
between testdigest and the main module, but Go allows for blackbox-testing
by using a "_test" package.
This patch:
- moves the test file to be next to the implementation.
- removes the redundant imports of "crypto/sha256" and "crypto/shasha512",
as they are imported by default since 084376bb543d4ce80b030a77a6f51f3b3fd861dc
Keep the linters happy:
- fix an unhandled error (but unlikely to happen)
- fix some variables being shadowed
Use sub-tests to not fail early if an algorithm fails.
With this change:
=== RUN   TestFroms
=== RUN   TestFroms/sha256
=== RUN   TestFroms/sha384
=== RUN   TestFroms/sha512
--- PASS: TestFroms (0.02s)
--- PASS: …

assorted (test) cleanups

---

.github/workflows/test.yml
blake3/go.mod
blake3/go.sum
go.mod

- follow-up to https://github.com/opencontainers/go-digest/pull/85 (https://github.com/opencontainers/go-digest/pull/85#issuecomment-1414448308)
These versions were really old, and all reached EOL; let's update the minimum version for the next release, so that we can also start taking advantage of newer Go features.

drop obsolete Go versions, and add go1.21

---

digest.go
digest_test.go
testdigest/testdigest.go

Digest: use strings.Cut, and remove Digest.sepIndex()

---

blake3/go.mod
blake3/go.sum

full diff: https://github.com/zeebo/blake3/compare/v0.1.1...v0.2.2

blake3: update to github.com/zeebo/blake3 v0.2.2

---

blake3/go.mod
blake3/go.sum

addresses CVE-2022-29526, even though we do not use `Faccessat()`

blake3: update go mod deps

---

algorithm.go
algorithm_test.go
digest.go
digest_test.go
digestset/set.go
digestset/set_test.go
testdigest/testdigest.go

- rename "digester" vars that shadowed package-level digester type
- rename "hexdigestbytes" to be properly camelCase
- update test to use "errors.Is()" instead of straight compare
No need to validate the format if we previously accepted it to be
registered.
Just for convenience ':-)
Before:
pkg: github.com/opencontainers/go-digest/digestset
BenchmarkAdd10-10              183613      6368 ns/op
BenchmarkAdd100-10              15739     75741 ns/op
BenchmarkAdd1000-10              1430    831884 ns/op
BenchmarkRemove10-10           169999      6984 ns/op
BenchmarkRemove100-10           15312     78299 ns/op
BenchmarkRemove1000-10           1470    815144 ns/op
BenchmarkLookup10-10         27067897        43.69 ns/op
BenchmarkLookup100-10        17203653        69.17 ns/op …

address some linting issues, and small refactor, performance optimizations

---

algorithm.go
digest_test.go
digestset/set_test.go

related:
- https://github.com/opencontainers/go-digest/pull/64
- https://github.com/opencontainers/go-digest/issues/91#issuecomment-1728133554
- https://github.com/opencontainers/distribution-spec/issues/494
The SHA-384 algorithm is not documented in the OCI image-spec ([1], [2]), and is not encouraged to be used. Commit 084376bb543d4ce80b030a77a6f51f3b3fd861dc registered all algorithms by default, but also included SHA-384.
This patch disables SHA-384 by default, to discourage its use.
[1]: https://github.com/opencontainers/image-spec/blob/v1.0.2/descriptor.md#digests
[2]: https://github.com/opencontainers/image-spec/blob/v1.0.2/descriptor.md#registered-algorithms

do not register sha384 by default
